при обработке исключений часто возникают ситуации, когда после блока `try` следует несколько блоков `catch` с одинаковым кодом.

Или может быть, например, 3 `catch`-блока с одним кодом и еще 2 `catch`-блока с другим. Стандартная в общем-то ситуация, когда у вас в проекте ответственно относятся к обработке исключений.

Начиная с 7-й версии, в язык Java добавили возможность указать несколько типов исключений в одном блоке `catch`. Выглядит это примерно так:

```java
try
{
   код, где может возникнуть ошибка
}
catch(ТипИсключения1 | ТипИсключения2 | ТипИсключения3 имя)
{
   код обработки исключений
}
```

Блоков `catch` может быть сколько угодно. Однако в одном блоке `catch` нельзя указать исключения, которые наследуются друг от друга. Т.е. нельзя написать catch (`Exception` | `RuntimeException` e), т.к. класс `RuntimeException` унаследован от `Exception`.

